### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AndreaMonzini** [Tagirijus/fountain2pdf#2]
Hello Manuel,
EDIT Add-on for writing screenplays in Blender:
https://github.com/tin2tin/Blender_Screenwriter

Could you add please a License?  ( MIT ? )

Thank you!
Andrea

**Comment by Tagirijus** [comment]
Hey Andrea, thanks for the hint. I just uploaded a license with commit:
https://github.com/Tagirijus/fountain2pdf/commit/abd55749c84fe41fa715db57db907a725a14fc5b
Have a nice day! (=
