### ISSUE TITLE
Don’t Overwrite Input File If It Has Nonstandard Extension

### ISSUE THREAD

**Issue by ldo** [Tagirijus/fountain2pdf#3]
I was just trying this out with a small test file which I called `try.fou`, and was dismayed to find that the input file was overwritten with the PDF output. Turns out the code is explicitly checking for a `.fountain` extension, and will not correctly generate the output filename if this is anything else.

The following patch generates the output file name by stripping the extension off the input name, regardless of what it might be.

[ldo-no-overwrite-output.patch.txt](https://github.com/Tagirijus/fountain2pdf/files/4051694/ldo-no-overwrite-output.patch.txt)

**Comment by Tagirijus** [comment]
Good point. Thank you for this fix! I applied your patch. (=
